[Database]
; В реальности тут будет зашифрованная строка, но пока для тестов пишем открытую.
; Замени Server_Name на имя твоего SQL сервера (например, localhost\SQLEXPRESS)
ConnectionString=Driver={ODBC Driver 17 for SQL Server};Server=DESKTOP-PKN6175\SQLEXPRESS;Database=FactoryManagementDB;Trusted_Connection=yes;